In [962]:
import numpy as np 
import pandas as pd 
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_auc_score

import warnings
warnings.filterwarnings("ignore")

In [963]:
train_df = pd.read_csv("training_set_features.csv")

In [964]:
train_df_res=pd.read_csv("training_set_labels.csv")

In [965]:
train_df.head()

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              0          1.0            0.0                        0.0   
1              1          3.0            2.0                        0.0   
2              2          1.0            1.0                        0.0   
3              3          1.0            1.0                        0.0   
4              4          2.0            1.0                        0.0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   0.0                   0.0                    0.0   
1                   1.0                   0.0                    1.0   
2                   1.0                   0.0                    0.0   
3                   1.0                   0.0                    1.0   
4                   1.0                   0.0                    1.0   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          0.0                      1.0   
1                          0.0                      1.0   
2                          0.0                      0.0   
3                          1.0                      0.0   
4                          1.0                      0.0   

   behavioral_touch_face  ...             income_poverty  marital_status  \
0                    1.0  ...              Below Poverty     Not Married   
1                    1.0  ...              Below Poverty     Not Married   
2                    0.0  ...  <= $75,000, Above Poverty     Not Married   
3                    0.0  ...              Below Poverty     Not Married   
4                    1.0  ...  <= $75,000, Above Poverty         Married   

   rent_or_own   employment_status  hhs_geo_region                census_msa  \
0          Own  Not in Labor Force        oxchjgsf                   Non-MSA   
1         Rent            Employed        bhuqouqj  MSA, Not Principle  City   
2          Own            Employed        qufhixun  MSA, Not Principle  City   
3         Rent  Not in Labor Force        lrircsnp       MSA, Principle City   
4          Own            Employed        qufhixun  MSA, Not Principle  City   

   household_adults  household_children  employment_industry  \
0               0.0                 0.0                  NaN   
1               0.0                 0.0             pxcmvdjn   
2               2.0                 0.0             rucpziij   
3               0.0                 0.0                  NaN   
4               1.0                 0.0             wxleyezf   

   employment_occupation  
0                    NaN  
1               xgwztkwe  
2               xtkaffoo  
3                    NaN  
4               emcorrxb  

[5 rows x 36 columns]

In [966]:
train_df.columns

Index(['respondent_id', 'xyz_concern', 'xyz_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'marital_status',
       'rent_or_own', 'employment_status', 'hhs_geo_region', 'census_msa',
       'household_adults', 'household_children', 'employment_industry',
       'employment_occupation'],
      dtype='object')

In [967]:
for i in train_df.columns:
    train_df[i].replace(np.nan,train_df[i].mode()[0],inplace=True)

In [968]:
for i in train_df.columns:
    k=0
    a=train_df[i].unique()
    a.sort()
    for j in a:
        train_df[i].replace(j,k,inplace=True)
        k+=1

In [969]:
train_df_res.columns

Index(['respondent_id', 'xyz_vaccine', 'seasonal_vaccine'], dtype='object')

In [970]:
X = train_df.drop(['respondent_id','doctor_recc_seasonal','opinion_seas_vacc_effective','opinion_seas_risk', 'opinion_seas_sick_from_vacc'], axis=1)
y = train_df_res['xyz_vaccine']

In [971]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.3)

In [972]:
print(y_train.value_counts())

xyz_vaccine
0    14667
1     4027
Name: count, dtype: int64


In [973]:
skmodel = GaussianNB()
skmodel.fit(X_train, y_train)

GaussianNB()

In [974]:
y_pred = skmodel.predict(X_val)

In [975]:
ra = roc_auc_score(y_val, y_pred)
print(f"ROC_AUC score: {ra}")

ROC_AUC score: 0.7066266487435814


In [976]:
X = train_df.drop(['respondent_id','doctor_recc_xyz','opinion_xyz_vacc_effective','opinion_xyz_risk', 'opinion_xyz_sick_from_vacc','xyz_concern', 'xyz_knowledge'], axis=1)
y = train_df_res['seasonal_vaccine']

In [977]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.3)

In [978]:
print(y_train.value_counts())

seasonal_vaccine
0    10065
1     8629
Name: count, dtype: int64


In [979]:
skmodel1 = GaussianNB()
skmodel1.fit(X_train, y_train)

GaussianNB()

In [980]:
y_pred = skmodel1.predict(X_val)

In [981]:
ra = roc_auc_score(y_val, y_pred)
print(f"ROC_AUC score: {ra}")

ROC_AUC score: 0.7391582742322839


In [982]:
test_df = pd.read_csv("test_set_features.csv")

In [983]:
test_df.shape

(26708, 36)

In [984]:
Index=test_df['respondent_id'].copy()
arr=Index.values

In [985]:
arr

array([26707, 26708, 26709, ..., 53412, 53413, 53414], dtype=int64)

In [986]:
for i in test_df.columns:
    test_df[i].replace(np.nan,test_df[i].mode()[0],inplace=True)

In [987]:
for i in test_df.columns:
    k=0
    a=test_df[i].unique()
    a.sort()
    for j in a:
        test_df[i].replace(j,k,inplace=True)
        k+=1

In [988]:
test_df_1=test_df.copy()
test_df.drop(['respondent_id','doctor_recc_seasonal','opinion_seas_vacc_effective','opinion_seas_risk', 'opinion_seas_sick_from_vacc'], axis=1,inplace=True)

In [989]:
y_test = skmodel.predict(test_df)

In [990]:
test_df_1.drop(['respondent_id','doctor_recc_xyz','opinion_xyz_vacc_effective','opinion_xyz_risk', 'opinion_xyz_sick_from_vacc','xyz_concern', 'xyz_knowledge'], axis=1,inplace=True)

In [991]:
y_test_2=skmodel1.predict(test_df_1)

In [992]:
y_test

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [993]:
arr

array([26707, 26708, 26709, ..., 53412, 53413, 53414], dtype=int64)

In [994]:
result = pd.DataFrame({
    'respondent_id': arr,
    'h1n1_vaccine': y_test,
    'seasonal_vaccine':y_test_2
})

In [995]:
result

respondent_id  h1n1_vaccine  seasonal_vaccine
0              26707             0                 0
1              26708             0                 0
2              26709             1                 1
3              26710             0                 1
4              26711             1                 1
...              ...           ...               ...
26703          53410             1                 1
26704          53411             0                 0
26705          53412             0                 0
26706          53413             0                 1
26707          53414             0                 1

[26708 rows x 3 columns]

In [996]:
result.to_csv("submission.csv", index=False) #(for making submission file)